# fly.toml app configuration file generated for onethousandserver on 2025-06-01T21:00:00+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'onethousandserver'
primary_region = 'waw'

[build]

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 8080
    handlers = ["tls"]

[[vm]]
  size = 'shared-cpu-1x'
